version: "3.8"

services:
  app:
    container_name: "quick-wine-quiz"
    hostname: "quick-wine-quiz-server"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
      - ./assets:/usr/local/apache2/htdocs/assets
      - ./quiz:/usr/local/apache2/htdocs/quiz
    networks:
      - default
